name: Docker Image CI

env:
  imageName: portainer.local:5000/github-runner:$(date +%s)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.imageName}}
    - name: Push the Docker image
      run: docker image push ${{env.imageName}}
